config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts do
    collection do
      get 'most_recent', as: :latest
    end
  end

  resources :writers do
  end

  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create]

  delete "/logout", to: "sessions#destroy", as: :logout

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :writer

  validates :title, presence: true

  def self.published
    return Post.where("publish_date < ?", Time.now)
  end

  def self.by_author(author_name)
    published_posts = Post.published
    return published_posts.where(author_name: author_name)
  end

  def self.most_recent
    Post.published.max_by do |p|
      p.publish_date
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/models/writer.rb
class Writer < ActiveRecord::Base
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_login
    if current_user.nil?
      flash[:error] = "You must be logged in to view this section"
      redirect_to new_session_path
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    # @favorite = current_user[:favorite_post]
    # @posts = Post.by_author("Charles")
    @posts = Post.all
    user_id = session[:user_id]
    if user_id.nil?
      # not logged in
      @user_name = "guest"
    else
      # logged in
      @user_name = User.find(user_id).first_name
    end
  end

  def show
    id = params[:id]
    @post = Post.find(id)
  end

  def edit
    redirect_to "http://google.com/"
    #render :edit_form
  end

  def new
    @post = Post.new
  end

  def create
    # Post.create(post_params[:post])

    @post = Post.new(post_params[:post])
    if @post.save
      redirect_to "/"
    else
      render "new"
      # redirect_to new_post_path
      # The above will take you to a brand new
      # form and won't save the info or errors
    end
  end

  def most_recent
    @post = Post.most_recent
    render :show
  end

  private

  def post_params
    params.permit(post:[:title, :writer_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  # before_action :require_login, only: [:destroy]

  def new

  end

  def create
    data = params[:session_data]
    @user = User.find_by_email(data[:email])

    if !@user.nil?
      # User is in the system
      if @user.authenticate(data[:password])
        # User is authenticated
        session[:user_id] = @user.id
        redirect_to root_path
      else
        # User is not authenticated
        flash.now[:error] = "Try Again!"
        render :new
      end
    else
      # User is not in the system
      flash[:error] = "Try to Create a New User"
      redirect_to new_user_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end











end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
    redirect_to root_path if @user.save
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit your Post</h1>

app/views/posts/edit_form.html.erb
<h1>Edit your Post</h1>

app/views/posts/index.html.erb
<h3>HELLO <%= @user_name %>, WE ARE RAILSING!</h3>
<%= link_to "Check out the most recent post!", latest_posts_path %>
<br>
<%= link_to "New Post!", new_post_path %>
<br>
<%= link_to "New User!", new_user_path %>
<br>
<%= link_to "Login!", new_session_path %>
<br>
<%= link_to "Logout!", logout_path, method: :delete %>
<br>
<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <td>Post Title</td>
      <td>Post Writer</td>
      <td>Post Creation Date</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
  <% @posts.each do |post| %>
  <tr>
  <td><%= post.title %></td>
  <td>
    <% if !post.writer.nil? %>
      <%= post.writer.name %>
    <% end %>
  </td>
  <td><%= post.created_at %></td>
  <td><%= link_to "View Post", post_path(post) %></td>
  </tr>
  <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<ul>
  <% @post.errors.each do |column, message| %>
    <li>
      <strong><%= column.capitalize %></strong> <%= message %>
    </li>
  <% end %>
</ul>

<%= form_for @post, :html => { :class => "form" } do |f| %>
  <fieldset>
    <legend>Post Information</legend>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :writer_id, "Writer" %>
      <%= f.collection_select(:writer_id, Writer.all, :id, :name,
        { prompt: "Select the Writer:" },
        { class: "form-control" } ) %>
    </div>
  </fieldset>
  <%= f.submit class: "btn btn-info" %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h5><%= @post.publish_date %><h5>

app/views/users/new.html.erb
<% if !flash[:error].nil? %>
  <%= flash[:error] %>
<% end %>

<ul>
  <% @user.errors.each do |column, message| %>
    <li>
      <strong><%= column.capitalize %></strong> <%= message %>
    </li>
  <% end %>
</ul>

<%= form_for @user do |f| %>
<div class="form-group">
  <%= f.label :first_name %>
  <%= f.text_field :first_name, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :last_name %>
  <%= f.text_field :last_name, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
</div>
  <%= f.submit class: "btn btn-info" %>
<% end %>